config/routes.rb
Blog::Application.routes.draw do
resources :posts

  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params.require(:post).permit(:title, :content))
		if @post.save
			redirect_to posts_url
		else
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @picture.update_attribues(params.require(:post).permit(:title, :content))
			redirect_to posts_url
		else
			render :edit
		end 

	end 

	def delete
		@post = Post.find(params[:id])
    	@post.destroy
    	redirect_to posts_url
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :content %>
		<%= form.text_area :content %>
	</p>
	<p>
		<%= form.submit "Save" %>
	</p>
<% end %>

<%= link_to "Go Back", posts_url %>

app/views/posts/index.html.erb
<h1>POSTS</h1>

<% @posts.each do |post| %>
	<%= link_to post [:title], post %><br />
	<%= post [:content] %><br />
	<br />
	<br />
<% end %>

<%= link_to "new", new_post_path %>

app/views/posts/new.html.erb
<h1>Make a New Post</h1>

<%= form_for @post do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :content %>
		<%= form.text_area :content %>
	</p>
	<p>
		<%= form.submit "Save" %>
	</p>
<% end %>

<%= link_to "Go Back", posts_url %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content%></p>
<p><%= @post.created_at%></p>

<p><%= link_to "Edit", edit_post_path %></p>
<p><%= link_to "Back to Posts", posts_url %></p>